### ISSUE TITLE
どちらをアサインして良いか迷うGMO IDのケース

### ISSUE THREAD

**Issue by okbp** [skwsm/gmo#3]
培地成分表に記載された名前または化学式で自動アサインでは複数のGMOにヒットしてしまうケースがある。どちらかのクラスまたはシノニムを削除する必要がある

#### 1. ''Na2B4O7"
* GMO_001187("Disodium tetraborate")
* GMO_002332("Sodium tetraborate")
Na2をみると"Disodium"側か？

#### 2. "amphotericin B"
* GMO_002086("Amphotericin B")
* GMO_002146("Amphotericin B")
2回新規登録しただけかも。どちらか一方削除でOKか

#### 3. "Murashige and Skoog plant salt mixture"
* GMO_001311("Murashige & Skoog's plant salt mixture")
* GMO_002216("Murashige and Skoog plant salt mixture")
同じものだと思うので、GMO_001311側にシノニム"Murashige and Skoog plant salt mixture"を追加してGMO_002216は削除すればいい

**Comment by skwsm** [comment]
GMO_001187 and GMO_002332,  GMO_002086 and GMO_002146, GMO_001311 and GMO_002216 refer to the same concept, respectively. I have made GMO_002332, GMO_002146, and GMO_002216 obsolete.
